Version: '1'

services:
#Gluetun VPN tunnel
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 1080:1080/tcp # Socks-5
      - 8112:8112/tcp # Deluge
    volumes:
      - /portainer/gluetun/config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER= #Change for your provider
      - OPENVPN_USER= #username from provider
      - OPENVPN_PASSWORD= #password from provider
      - SERVER_REGIONS=US Houston,US Texas #preferred server location
    restart: unless-stopped

#Deluge Torrent downloader
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    networks: gluetun_1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /portainer/deluge/config:/config
      - /mnt/media/downloads:/downloads
    restart: unless-stopped

#Prolwarr torrent indexer  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /portainer/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

#Radarr movie library manager  
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /portainer/radarr/config:/config
      - /mnt/media/movies:/movies #optional
      - /mnt/media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

#Sonarr tv show library manager
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /portainer/sonarr/config:/config
      - /mnt/media/tv:/tv #optional
      - /mnt/media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

#Jellyfin hosted media player and user interface
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /portainer/jellyfin/config:/config
      - /mnt/media/tv:/data/tvshows
      - /mnt/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
    restart: unless-stopped

#Jellyseer avaliable media request and display 
  jellyseer:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /portainer/jellyseer/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped

#Flaresolver proxy for prowlarr 
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=LOG_LEVEL:-info
      - LOG_HTML=LOG_HTML:-false
      - CAPTCHA_SOLVER=CAPTCHA_SOLVER:-none
      - TZ=America/Chicago
    ports:
      - 8191:8191
    restart: unless-stopped

# networks:
#     default:
#         external:
#             name: $DEFAULT_NETWORK