Version: '1'

services:

#wireguard VPN server
  wireguard:
    environment:
      - WG_HOST= #Your Public IP
      - PASSWORD=${PASSWORD}
      - WG_PORT=563
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=192.168.0.0/24,10.0.1.0/24 #replace with your home network ip prange 
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /portainer/wireguard/config:/etc/wireguard
    ports:
      - "563:51820/udp" #you will need to port forward port 563 on your router, you could also try 123/udp and 51820/udp if you have trouble
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

#ADguard Home DNS sinkhole that protects devices from unwanted content
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    volumes:
      - /portainer/adguard/conf:/opt/adguardhome/conf
      - /portainer/adguard/opt:/opt/adguardhome/work
    ports:
      # # DNS
      - 53:53/tcp
      - 53:53/udp
      # # DHCP server
      # - 67:67/udp
      # - 68:68/udp
      # # HTTPS/DNS-over-HTTPS
      - 443:443/tcp
      # # DNS-over-TLS
      - 853:853/tcp
      # # DNS-over-QUIC
      - 853:853/udp
      # # DNSCrypt
      - 5443:5443/tcp
      - 5443:5443/udp
      # WebUI
      - 3000:3000/tcp
    restart: unless-stopped
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.adguardhome.entrypoints=insecure"
      # - "traefik.http.routers.adguardhome.rule=Host(`adguard.$DOMAIN`)"
      # - "traefik.http.services.adguardhome.loadbalancer.server.port=3000"
      # - "traefik.http.routers.adguardhome.tls.certresolver=le"

# networks:
#     default:
#         external:
#             name: $DEFAULT_NETWORK

