Version: '1'

services:

# wireguard VPN server
  wireguard:
    environment:
      - WG_HOST= #Your Public IP
      - PASSWORD=${PASSWORD}
      - WG_PORT=563
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=192.168.0.0/24,10.0.1.0/24 #replace with your home network ip prange 
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /portainer/wireguard/config:/etc/wireguard
    ports:
      - "563:51820/udp" # you will need to port forward port 563 on your router, you could also try 123/udp and 51820/udp if you have trouble
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

# PI Hole DNS sinkhole that protects devices from unwanted content
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: #'{Secure password else random}'
    volumes:
      - /portainer/pihole/config:/etc/pihole
      - /portainer/pihole/config:/etc/dnsmasq.d'
    restart: unless-stopped

#Traefik Edge Router that makes publishing your services a fun and easy experience
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8080:8080/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"